dist: bionic
language: java
script: ant travis

jdk:
- openjdk9
- openjdk10
- openjdk11
- oraclejdk11

addons:
  apt:
    packages:
    - picosat
    - minisat

before_script:
- ant -version

sudo: false

notifications:
  email: false
